import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import {ClerkProvider} from "@clerk/nextjs";
import { Variable } from "lucide-react";
import Head from "next/head";
import { Toaster } from 'react-hot-toast';
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Leetcode",
  description: "Generated by create next app",
  icons:{
    icon:["/favicon.ico?v=4"],

  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      layout:{
        logoImageUrl:'/leetcode.png',
        socialButtonsVariant:"iconButton"

      },
      variables:{
        colorText:'#ffffff',
          colorPrimary:"#FF5733",
          colorBackground:"#262626",
          colorInputText:"#ffffff",
          

      }
    }}
    >
      <html lang="en" suppressHydrationWarning>
       
        
      <body className={cn(
         "min-h-screen bg-background font-sans antialiased",
        fontSans.variable,

      )} >
        <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem
        disableTransitionOnChange

        >
      
        <Navbar/>
        
        {children}
        <Toaster  position="bottom-left" />
        </ThemeProvider>
        
        </body>
    </html>
    </ClerkProvider>
    
  );
}
